import { useState, useEffect, useRef } from 'react';

/* Helpers — mirrors report.js */
function formatRpDate(d) {
  const day = String(d.getDate()).padStart(2, '0');
  const mon = d.toLocaleString('en', { month: 'short' });
  const yr  = d.getFullYear();
  const h   = String(d.getHours()).padStart(2, '0');
  const m   = String(d.getMinutes()).padStart(2, '0');
  return `${day} ${mon} ${yr}, ${h}:${m}`;
}

function randomSize() {
  return `${(Math.random() * 3 + 0.4).toFixed(1)} MB`;
}

/*
 * ReportSection — mirrors #page-report from project.html + report.js
 *
 * Props:
 *  activeVersion    — string for version badge
 *  isActive         — boolean
 *  autoGenerate     — boolean: when true, generate a report immediately
 *  onAutoGenerateDone — fn() called after the auto-generate fires
 */
export default function ReportSection({ activeVersion, isActive, autoGenerate, onAutoGenerateDone }) {
  const [reports, setReports] = useState([]);
  const rpCounterRef = useRef(0);

  /* Auto-generate when navigated from Planning via "Create Report" */
  useEffect(() => {
    if (autoGenerate) {
      generateReport();
      onAutoGenerateDone?.();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate]);

  function generateReport() {
    rpCounterRef.current += 1;
    const counter = rpCounterRef.current;
    const now = new Date();
    const id = Date.now() + Math.random(); // ensure unique even if called twice quickly

    const report = {
      id,
      name: `Report ${counter}`,
      date: formatRpDate(now),
      status: 'generating',
      size: '—',
    };

    setReports(prev => [report, ...prev]);

    // Simulate generation: 1.8s → final
    setTimeout(() => {
      setReports(prev => prev.map(r =>
        r.id === id ? { ...r, status: 'final', size: randomSize() } : r
      ));
    }, 1800);
  }

  function deleteReport(id) {
    setReports(prev => prev.filter(r => r.id !== id));
  }

  function renameReport(id, newName) {
    setReports(prev => prev.map(r =>
      r.id === id ? { ...r, name: newName || r.name } : r
    ));
  }

  function downloadReport(id) {
    const r = reports.find(x => x.id === id);
    if (!r || r.status === 'generating') return;
    const content = `C2P Report\nName: ${r.name}\nGenerated: ${r.date}\nStatus: ${r.status}\n`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${r.name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function getBadgeClass(status) {
    return `rp-badge rp-badge--${status}`;
  }

  function getBadgeLabel(status) {
    if (status === 'generating') return 'Generating…';
    if (status === 'draft') return 'Draft';
    return 'Final';
  }

  return (
    <section className={`page-section${isActive ? ' active' : ''}`} id="page-report">

      {/* Header */}
      <div className="page-header">
        <div className="page-header__left">
          <h2 className="page-section-title">Reports</h2>
          <p className="page-section-sub">Generated reports for this project version</p>
        </div>
        <div className="page-header__right" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <button className="rp-btn-generate" onClick={generateReport}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
              <line x1="12" y1="18" x2="12" y2="12"/>
              <line x1="9" y1="15" x2="15" y2="15"/>
            </svg>
            Generate Report
          </button>
        </div>
      </div>

      {/* Report list panel */}
      <div className="rp-list-panel">

        {/* Panel header */}
        <div className="rp-panel-header">
          <span className="rp-col rp-col--icon"></span>
          <span className="rp-col rp-col--name">Report Name</span>
          <span className="rp-col rp-col--date">Generated</span>
          <span className="rp-col rp-col--status">Status</span>
          <span className="rp-col rp-col--size">Size</span>
          <span className="rp-col rp-col--actions"></span>
        </div>

        {/* Dynamic report rows */}
        <div className="rp-list-body" id="rpListBody">

          {/* Empty state */}
          {reports.length === 0 && (
            <div className="rp-empty-state" id="rpEmptyState">
              <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="16" y1="13" x2="8" y2="13"/>
                <line x1="16" y1="17" x2="8" y2="17"/>
                <polyline points="10 9 9 9 8 9"/>
              </svg>
              <p>No reports yet.</p>
              <span>Click <strong>Generate Report</strong> to create one from the current process plan.</span>
            </div>
          )}

          {reports.map((report) => (
            <div key={report.id} className="rp-row">
              {/* File icon */}
              <div className="rp-file-icon">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                </svg>
              </div>

              {/* Report name (editable) */}
              <span
                className="rp-name"
                contentEditable
                suppressContentEditableWarning
                spellCheck={false}
                onBlur={(e) => renameReport(report.id, e.currentTarget.textContent.trim())}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); e.target.blur(); } }}
              >
                {report.name}
              </span>

              {/* Date */}
              <span className="rp-date">{report.date}</span>

              {/* Status badge */}
              <span className="rp-status">
                <span className={getBadgeClass(report.status)}>
                  <span className="rp-badge-dot"></span>
                  {getBadgeLabel(report.status)}
                </span>
              </span>

              {/* Size */}
              <span className="rp-size">{report.size}</span>

              {/* Actions */}
              <div className="rp-actions">
                <button
                  className="rp-action-btn"
                  onClick={() => downloadReport(report.id)}
                  title="Download"
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                    <polyline points="7 10 12 15 17 10"/>
                    <line x1="12" y1="15" x2="12" y2="3"/>
                  </svg>
                </button>
                <button
                  className="rp-action-btn rp-action-btn--del"
                  onClick={() => deleteReport(report.id)}
                  title="Delete"
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6"/>
                    <path d="M19 6l-1 14H6L5 6"/>
                    <path d="M10 11v6M14 11v6"/>
                    <path d="M9 6V4h6v2"/>
                  </svg>
                </button>
              </div>
            </div>
          ))}

        </div>

      </div>

    </section>
  );
}
