import { useState, useEffect } from 'react';

function formatReportDate(value) {
  if (!value) return '—';
  return new Date(value).toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

function reportToText(report) {
  const data = report.reportData || {};
  const part = data.partDefinition || {};
  const processPlan = data.processPlan || {};
  const setups = (processPlan.setups || []).map((setup) => [
    `SETUP ${setup.sequence}: ${setup.purpose || 'Manufacturing setup'}`,
    `Machine: ${setup.machine || 'Not specified'}`,
    `Workholding: ${setup.workholding || 'Not specified'}`,
    ...(setup.operations || []).map((operation) => `  ${operation.sequence}. ${operation.name} | ${operation.processFamily || '—'} | Inspection: ${operation.inspection || '—'}`),
  ].join('\n')).join('\n\n');

  return [
    'C2P ENGINEERING PROCESS REPORT',
    `Generated: ${formatReportDate(report.createdAt)}`,
    `Part: ${part.partName || '—'} (${part.partNumber || 'No part number'})`,
    `Material: ${part.material || '—'} | Units: ${part.drawingUnits || '—'}`,
    '',
    'EXECUTIVE SUMMARY',
    data.executiveSummary || '—',
    '',
    'PROCESS STRATEGY',
    processPlan.strategy || '—',
    setups,
    '',
    'QUALITY CHECKPOINTS',
    (processPlan.qualityCheckpoints || []).join('\n') || '—',
    '',
    'RISKS AND ASSUMPTIONS',
    (data.risksAndAssumptions || []).join('\n') || '—',
    '',
    'RELEASE RECOMMENDATION',
    data.releaseRecommendation || '—',
  ].join('\n');
}

/*
 * ReportSection — mirrors #page-report from project.html + report.js
 *
 * Props:
 *  activeVersion    — string for version badge
 *  isActive         — boolean
 *  autoGenerate     — boolean: when true, generate a report immediately
 *  onAutoGenerateDone — fn() called after the auto-generate fires
 */
export default function ReportSection({ projectId, activeVersion, isActive, autoGenerate, onAutoGenerateDone }) {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [selectedReport, setSelectedReport] = useState(null);

  useEffect(() => {
    if (!isActive || !projectId) return;
    loadReports();
  }, [isActive, projectId]);

  useEffect(() => {
    if (autoGenerate && isActive) {
      generateReport();
      onAutoGenerateDone?.();
    }
  }, [autoGenerate, isActive]);

  async function loadReports() {
    setLoading(true);
    setError('');
    try {
      const response = await fetch(`http://localhost:3000/api/projects/${projectId}/reports`);
      const payload = await response.json();
      if (!response.ok || payload.success === false) throw new Error(payload.message || 'Unable to load reports');
      setReports(payload.data || []);
    } catch (loadError) {
      setError(loadError.message);
    } finally {
      setLoading(false);
    }
  }

  async function generateReport() {
    setGenerating(true);
    setError('');
    try {
      const response = await fetch(`http://localhost:3000/api/projects/${projectId}/reports/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      const payload = await response.json();
      if (!response.ok || payload.success === false) throw new Error(payload.message || 'Unable to generate report');
      const report = payload.data;
      setReports(prev => [report, ...prev]);
      setSelectedReport(report);
    } catch (generationError) {
      setError(generationError.message);
    } finally {
      setGenerating(false);
    }
  }

  function downloadReport(report) {
    const content = reportToText(report);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `c2p_engineering_report_${report._id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <section className={`page-section${isActive ? ' active' : ''}`} id="page-report">

      {/* Header */}
      <div className="page-header">
        <div className="page-header__left">
          <h2 className="page-section-title">Reports</h2>
          <p className="page-section-sub">Generated reports for this project version</p>
        </div>
        <div className="page-header__right" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <button className="rp-btn-generate" onClick={generateReport} disabled={generating}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
              <line x1="12" y1="18" x2="12" y2="12"/>
              <line x1="9" y1="15" x2="15" y2="15"/>
            </svg>
            {generating ? 'Preparing Document…' : 'Generate Report'}
          </button>
        </div>
      </div>

      {/* Report list panel */}
      <div className="rp-list-panel">

        {/* Panel header */}
        <div className="rp-panel-header">
          <span className="rp-col rp-col--icon"></span>
          <span className="rp-col rp-col--name">Report Name</span>
          <span className="rp-col rp-col--date">Generated</span>
          <span className="rp-col rp-col--status">Status</span>
          <span className="rp-col rp-col--size">Size</span>
          <span className="rp-col rp-col--actions"></span>
        </div>

        {/* Dynamic report rows */}
        <div className="rp-list-body" id="rpListBody">

          {/* Empty state */}
          {loading && <div className="rp-empty-state"><p>Loading engineering reports...</p></div>}
          {!loading && reports.length === 0 && (
            <div className="rp-empty-state" id="rpEmptyState">
              <svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="16" y1="13" x2="8" y2="13"/>
                <line x1="16" y1="17" x2="8" y2="17"/>
                <polyline points="10 9 9 9 8 9"/>
              </svg>
              <p>No reports yet.</p>
              <span>Generate a source-grounded document from verified extraction and process planning.</span>
            </div>
          )}

          {reports.map((report) => (
            <div key={report._id} className="rp-row" onClick={() => setSelectedReport(report)}>
              {/* File icon */}
              <div className="rp-file-icon">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                </svg>
              </div>

              {/* Report name (editable) */}
              <span
                className="rp-name"
              >
                Engineering Process Report
              </span>

              {/* Date */}
              <span className="rp-date">{formatReportDate(report.createdAt)}</span>

              {/* Status badge */}
              <span className="rp-status">
                <span className="rp-badge rp-badge--final">
                  <span className="rp-badge-dot"></span>
                  {report.status}
                </span>
              </span>

              {/* Size */}
              <span className="rp-size">v{report.metadata?.processPlanVersion || '—'}</span>

              {/* Actions */}
              <div className="rp-actions">
                <button
                  className="rp-action-btn"
                  onClick={(event) => { event.stopPropagation(); downloadReport(report); }}
                  title="Download"
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                    <polyline points="7 10 12 15 17 10"/>
                    <line x1="12" y1="15" x2="12" y2="3"/>
                  </svg>
                </button>
              </div>
            </div>
          ))}

        </div>

      </div>

      {error && <div className="demo-callout demo-callout--error">{error}</div>}

      {selectedReport && (
        <article className="rp-document-preview">
          <div className="rp-document-header">
            <div>
              <span className="demo-label">C2P ENGINEERING DOCUMENT</span>
              <h3>{selectedReport.reportData?.partDefinition?.partName || 'Manufacturing Process Report'}</h3>
              <p>Verified extraction + validated process plan | Generated {formatReportDate(selectedReport.createdAt)}</p>
            </div>
            <button className="rp-btn-generate" onClick={() => downloadReport(selectedReport)}>Download Document</button>
          </div>
          <div className="rp-document-grid">
            <div><span>Part Number</span><strong>{selectedReport.reportData?.partDefinition?.partNumber || '—'}</strong></div>
            <div><span>Material</span><strong>{selectedReport.reportData?.partDefinition?.material || '—'}</strong></div>
            <div><span>Context Version</span><strong>v{selectedReport.metadata?.contextVersion || '—'}</strong></div>
            <div><span>Plan Version</span><strong>v{selectedReport.metadata?.processPlanVersion || '—'}</strong></div>
          </div>
          <section className="rp-document-section"><span className="demo-label">Executive Summary</span><p>{selectedReport.reportData?.executiveSummary || '—'}</p></section>
          <section className="rp-document-section"><span className="demo-label">Process Strategy</span><p>{selectedReport.reportData?.processPlan?.strategy || '—'}</p></section>
          <section className="rp-document-section"><span className="demo-label">Release Recommendation</span><p>{selectedReport.reportData?.releaseRecommendation || '—'}</p></section>
        </article>
      )}

    </section>
  );
}
