// C2P Phase 1 â€” Process Planning Ontology Enums

export enum MaterialFamily {
  CARBON_STEEL = 'CARBON_STEEL',
  ALLOY_STEEL = 'ALLOY_STEEL',
  STAINLESS_STEEL = 'STAINLESS_STEEL',
  TOOL_STEEL = 'TOOL_STEEL',
  CAST_IRON = 'CAST_IRON',
  DUCTILE_IRON = 'DUCTILE_IRON',
  ALUMINUM_ALLOY = 'ALUMINUM_ALLOY',
  TITANIUM_ALLOY = 'TITANIUM_ALLOY',
  NICKEL_ALLOY = 'NICKEL_ALLOY',
  COPPER_ALLOY = 'COPPER_ALLOY',
  POLYMER = 'POLYMER',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}

export enum MaterialCondition {
  AS_RECEIVED = 'AS_RECEIVED',
  ANNEALED = 'ANNEALED',
  NORMALIZED = 'NORMALIZED',
  STRESS_RELIEVED = 'STRESS_RELIEVED',
  PRE_HARDENED = 'PRE_HARDENED',
  THROUGH_HARDENED = 'THROUGH_HARDENED',
  TEMPERED = 'TEMPERED',
  CASE_HARDENED = 'CASE_HARDENED',
  CARBURIZED = 'CARBURIZED',
  NITRIDED = 'NITRIDED',
  INDUCTION_HARDENED = 'INDUCTION_HARDENED',
  VACUUM_HARDENED = 'VACUUM_HARDENED',
  UNKNOWN = 'UNKNOWN',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  NOT_YET_DEFINED = 'NOT_YET_DEFINED',
}

export enum StockForm {
  ROUND_BAR = 'ROUND_BAR',
  SQUARE_BAR = 'SQUARE_BAR',
  RECTANGULAR_BILLET = 'RECTANGULAR_BILLET',
  PLATE = 'PLATE',
  TUBE = 'TUBE',
  CASTING = 'CASTING',
  FORGING = 'FORGING',
  EXTRUSION = 'EXTRUSION',
  SHEET = 'SHEET',
  CUSTOM_PRE_FORM = 'CUSTOM_PRE_FORM',
  UNKNOWN = 'UNKNOWN',
}

export enum GeometryType {
  PLANAR_FACE = 'PLANAR_FACE',
  EXTERNAL_CYLINDER = 'EXTERNAL_CYLINDER',
  INTERNAL_CYLINDER = 'INTERNAL_CYLINDER',
  EXTERNAL_TAPER = 'EXTERNAL_TAPER',
  INTERNAL_TAPER = 'INTERNAL_TAPER',
  SHOULDER = 'SHOULDER',
  STEP = 'STEP',
  SLOT = 'SLOT',
  KEYWAY = 'KEYWAY',
  POCKET = 'POCKET',
  CAVITY = 'CAVITY',
  RIB = 'RIB',
  THROUGH_HOLE = 'THROUGH_HOLE',
  BLIND_HOLE = 'BLIND_HOLE',
  DEEP_HOLE = 'DEEP_HOLE',
  RADIAL_HOLE = 'RADIAL_HOLE',
  CROSS_HOLE = 'CROSS_HOLE',
  THREAD_EXTERNAL = 'THREAD_EXTERNAL',
  THREAD_INTERNAL = 'THREAD_INTERNAL',
  GROOVE = 'GROOVE',
  CIRCLIP_GROOVE = 'CIRCLIP_GROOVE',
  CHAMFER = 'CHAMFER',
  FILLET = 'FILLET',
  COUNTERBORE = 'COUNTERBORE',
  COUNTERSINK = 'COUNTERSINK',
  BORE = 'BORE',
  GEAR_TEETH = 'GEAR_TEETH',
  FREEFORM_SURFACE = 'FREEFORM_SURFACE',
  SEALING_SURFACE = 'SEALING_SURFACE',
  CUSTOM_FEATURE = 'CUSTOM_FEATURE',
  UNKNOWN = 'UNKNOWN',
}

export enum FunctionalRole {
  BEARING_SEAT = 'BEARING_SEAT',
  TORQUE_TRANSMISSION = 'TORQUE_TRANSMISSION',
  SEALING_INTERFACE = 'SEALING_INTERFACE',
  FASTENER_INTERFACE = 'FASTENER_INTERFACE',
  LOCATING_INTERFACE = 'LOCATING_INTERFACE',
  ROTATIONAL_REFERENCE = 'ROTATIONAL_REFERENCE',
  LUBRICATION_CHANNEL = 'LUBRICATION_CHANNEL',
  FLUID_CHANNEL = 'FLUID_CHANNEL',
  MOUNTING_INTERFACE = 'MOUNTING_INTERFACE',
  STRUCTURAL_INTERFACE = 'STRUCTURAL_INTERFACE',
  WEIGHT_REDUCTION = 'WEIGHT_REDUCTION',
  RETENTION = 'RETENTION',
  CUSTOM = 'CUSTOM',
  UNKNOWN = 'UNKNOWN',
}

export enum RequirementType {
  DIMENSION = 'DIMENSION',
  DIMENSIONAL_TOLERANCE = 'DIMENSIONAL_TOLERANCE',
  GEOMETRIC_TOLERANCE = 'GEOMETRIC_TOLERANCE',
  SURFACE_ROUGHNESS = 'SURFACE_ROUGHNESS',
  HARDNESS = 'HARDNESS',
  CASE_DEPTH = 'CASE_DEPTH',
  ROUNDNESS = 'ROUNDNESS',
  CYLINDRICITY = 'CYLINDRICITY',
  FLATNESS = 'FLATNESS',
  PARALLELISM = 'PARALLELISM',
  PERPENDICULARITY = 'PERPENDICULARITY',
  CONCENTRICITY = 'CONCENTRICITY',
  RUNOUT = 'RUNOUT',
  POSITION = 'POSITION',
  THREAD_CLASS = 'THREAD_CLASS',
  CUSTOM = 'CUSTOM',
  UNKNOWN = 'UNKNOWN',
}

export enum DatumType {
  PLANAR = 'PLANAR',
  AXIAL = 'AXIAL',
  CYLINDRICAL_AXIS = 'CYLINDRICAL_AXIS',
  CENTER = 'CENTER',
  POINT = 'POINT',
  LINE = 'LINE',
  CUSTOM = 'CUSTOM',
}

export enum ReferenceRole {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  TERTIARY = 'TERTIARY',
  MANUFACTURING_REFERENCE = 'MANUFACTURING_REFERENCE',
  INSPECTION_REFERENCE = 'INSPECTION_REFERENCE',
}

export enum ManufacturingStateLabel {
  RAW = 'RAW',
  ROUGH_MACHINED = 'ROUGH_MACHINED',
  SEMI_FINISHED = 'SEMI_FINISHED',
  STRESS_RELIEVED = 'STRESS_RELIEVED',
  HEAT_TREATED = 'HEAT_TREATED',
  PRECISION_FINISHED = 'PRECISION_FINISHED',
  GROUND = 'GROUND',
  DEBURRED = 'DEBURRED',
  INSPECTED = 'INSPECTED',
  CUSTOM = 'CUSTOM',
}

export enum SetupStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum ProcessFamily {
  TURNING = 'TURNING',
  MILLING = 'MILLING',
  DRILLING = 'DRILLING',
  REAMING = 'REAMING',
  BORING = 'BORING',
  THREADING = 'THREADING',
  THREAD_MILLING = 'THREAD_MILLING',
  BROACHING = 'BROACHING',
  HOBBING = 'HOBBING',
  GRINDING = 'GRINDING',
  HARD_TURNING = 'HARD_TURNING',
  EDM = 'EDM',
  DEBURRING = 'DEBURRING',
  CLEANING = 'CLEANING',
  HEAT_TREATMENT = 'HEAT_TREATMENT',
  INSPECTION = 'INSPECTION',
  CUSTOM = 'CUSTOM',
}

export enum ProcessStage {
  ROUGHING = 'ROUGHING',
  SEMI_FINISHING = 'SEMI_FINISHING',
  FINISHING = 'FINISHING',
  PRECISION_FINISHING = 'PRECISION_FINISHING',
  FORMING = 'FORMING',
  THERMAL_PROCESSING = 'THERMAL_PROCESSING',
  SURFACE_FINISHING = 'SURFACE_FINISHING',
  INSPECTION = 'INSPECTION',
  SECONDARY_PROCESS = 'SECONDARY_PROCESS',
  CUSTOM = 'CUSTOM',
}

export enum AllowanceType {
  RADIAL = 'RADIAL',
  DIAMETRAL = 'DIAMETRAL',
  AXIAL = 'AXIAL',
  SURFACE = 'SURFACE',
  VOLUMETRIC = 'VOLUMETRIC',
  CUSTOM = 'CUSTOM',
}

export enum DependencyType {
  MUST_OCCUR_BEFORE = 'MUST_OCCUR_BEFORE',
  MUST_OCCUR_AFTER = 'MUST_OCCUR_AFTER',
  SAME_SETUP_PREFERRED = 'SAME_SETUP_PREFERRED',
  SAME_DATUM_REQUIRED = 'SAME_DATUM_REQUIRED',
  REQUIRES_STATE = 'REQUIRES_STATE',
  BLOCKED_BY = 'BLOCKED_BY',
  REQUIRES_INSPECTION = 'REQUIRES_INSPECTION',
  CUSTOM = 'CUSTOM',
}

export enum FeasibilityStatus {
  UNKNOWN = 'UNKNOWN',
  POTENTIALLY_FEASIBLE = 'POTENTIALLY_FEASIBLE',
  FEASIBLE = 'FEASIBLE',
  NOT_FEASIBLE = 'NOT_FEASIBLE',
}

export enum SelectionStatus {
  CANDIDATE = 'CANDIDATE',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  NOT_YET_EVALUATED = 'NOT_YET_EVALUATED',
}

export enum MachineCategory {
  LATHE = 'LATHE',
  MACHINING_CENTER = 'MACHINING_CENTER',
  MILLING_MACHINE = 'MILLING_MACHINE',
  GRINDING_MACHINE = 'GRINDING_MACHINE',
  BROACHING_MACHINE = 'BROACHING_MACHINE',
  HEAT_TREATMENT_FURNACE = 'HEAT_TREATMENT_FURNACE',
  CMM = 'CMM',
  CUSTOM = 'CUSTOM',
  UNKNOWN = 'UNKNOWN',
}

export enum WorkholdingType {
  THREE_JAW_CHUCK = 'THREE_JAW_CHUCK',
  FOUR_JAW_CHUCK = 'FOUR_JAW_CHUCK',
  SOFT_JAWS = 'SOFT_JAWS',
  COLLET_CHUCK = 'COLLET_CHUCK',
  HYDRAULIC_CHUCK = 'HYDRAULIC_CHUCK',
  LIVE_CENTER = 'LIVE_CENTER',
  DEAD_CENTER = 'DEAD_CENTER',
  BETWEEN_CENTERS = 'BETWEEN_CENTERS',
  VICE = 'VICE',
  SOFT_JAW_VICE = 'SOFT_JAW_VICE',
  VACUUM_FIXTURE = 'VACUUM_FIXTURE',
  MAGNETIC_CHUCK = 'MAGNETIC_CHUCK',
  MANDREL = 'MANDREL',
  EXPANDING_MANDREL = 'EXPANDING_MANDREL',
  ARBOR = 'ARBOR',
  TOMBSTONE_FIXTURE = 'TOMBSTONE_FIXTURE',
  CUSTOM_FIXTURE = 'CUSTOM_FIXTURE',
  SACRIFICIAL_SUBPLATE = 'SACRIFICIAL_SUBPLATE',
  GUIDE_BUSHING = 'GUIDE_BUSHING',
  CUSTOM = 'CUSTOM',
}

export enum ToolCategory {
  TURNING_INSERT = 'TURNING_INSERT',
  MILLING_CUTTER = 'MILLING_CUTTER',
  DRILL = 'DRILL',
  REAMER = 'REAMER',
  BORING_BAR = 'BORING_BAR',
  THREADING_TOOL = 'THREADING_TOOL',
  BROACH = 'BROACH',
  GRINDING_WHEEL = 'GRINDING_WHEEL',
  CUSTOM = 'CUSTOM',
}

export enum InstrumentType {
  VERNIER_CALIPER = 'VERNIER_CALIPER',
  DIGITAL_CALIPER = 'DIGITAL_CALIPER',
  OUTSIDE_MICROMETER = 'OUTSIDE_MICROMETER',
  INSIDE_MICROMETER = 'INSIDE_MICROMETER',
  BORE_GAUGE = 'BORE_GAUGE',
  HEIGHT_GAUGE = 'HEIGHT_GAUGE',
  DIAL_INDICATOR = 'DIAL_INDICATOR',
  TEST_INDICATOR = 'TEST_INDICATOR',
  CMM = 'CMM',
  TOUCH_PROBE = 'TOUCH_PROBE',
  AIR_GAUGE = 'AIR_GAUGE',
  ROUNDNESS_TESTER = 'ROUNDNESS_TESTER',
  SURFACE_ROUGHNESS_TESTER = 'SURFACE_ROUGHNESS_TESTER',
  HARDNESS_TESTER = 'HARDNESS_TESTER',
  THREAD_PITCH_GAUGE = 'THREAD_PITCH_GAUGE',
  THREAD_RING_GAUGE = 'THREAD_RING_GAUGE',
  THREAD_PLUG_GAUGE = 'THREAD_PLUG_GAUGE',
  GO_NO_GO_GAUGE = 'GO_NO_GO_GAUGE',
  OPTICAL_MEASUREMENT = 'OPTICAL_MEASUREMENT',
  CUSTOM = 'CUSTOM',
}

export enum HeatTreatmentType {
  STRESS_RELIEF = 'STRESS_RELIEF',
  ANNEALING = 'ANNEALING',
  NORMALIZING = 'NORMALIZING',
  THROUGH_HARDENING = 'THROUGH_HARDENING',
  TEMPERING = 'TEMPERING',
  CARBURIZING = 'CARBURIZING',
  CASE_HARDENING = 'CASE_HARDENING',
  NITRIDING = 'NITRIDING',
  INDUCTION_HARDENING = 'INDUCTION_HARDENING',
  VACUUM_HARDENING = 'VACUUM_HARDENING',
  CUSTOM = 'CUSTOM',
}

export enum QualityScope {
  PART = 'PART',
  FEATURE = 'FEATURE',
  OPERATION = 'OPERATION',
  FINAL_PRODUCT = 'FINAL_PRODUCT',
}

export enum InspectionStage {
  INCOMING_INSPECTION = 'INCOMING_INSPECTION',
  FIRST_ARTICLE = 'FIRST_ARTICLE',
  IN_PROCESS = 'IN_PROCESS',
  POST_OPERATION = 'POST_OPERATION',
  POST_HEAT_TREATMENT = 'POST_HEAT_TREATMENT',
  FINAL_INSPECTION = 'FINAL_INSPECTION',
}

export enum FailureAction {
  CONTINUE = 'CONTINUE',
  HOLD = 'HOLD',
  REWORK = 'REWORK',
  SCRAP = 'SCRAP',
  ENGINEERING_REVIEW = 'ENGINEERING_REVIEW',
}

export enum CriticalityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ProductionType {
  PROTOTYPE = 'PROTOTYPE',
  SMALL_BATCH = 'SMALL_BATCH',
  SERIES = 'SERIES',
  MASS_PRODUCTION = 'MASS_PRODUCTION',
}

export enum PartStatus {
  DRAFT = 'DRAFT',
  IN_PLANNING = 'IN_PLANNING',
  PLANNED = 'PLANNED',
  RELEASED = 'RELEASED',
}

export enum OperationStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum ProcessRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}
